language: node_js
node_js:
  - "8"
notifications:
  email:
    on_success: change
    on_failure: change
install:
  - npm i -g vsce
script:
  - vsce package
deploy:
  - provider: script
    skip_cleanup: true
    script: bash scripts/version.sh
    on:
      branch: master
      repo: smockle/xcode-default-theme
      tags: false
  - provider: script
    skip_cleanup: true
    script: bash scripts/publish.sh
    on:
      branch: master
      repo: smockle/xcode-default-theme
      tags: false
