name: Publish
on:
  push:
    branches: ["master"]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Get sources
        if: contains(github.event.commits[0].message, '[skip ci]') == false
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Build
        if: contains(github.event.commits[0].message, '[skip ci]') == false
        uses: "lannonbr/vsce-action@75a30e358888a882724b568c7fcc80d7f087906c"
        with:
          args: "package"

      - name: Bump version
        if: contains(github.event.commits[0].message, '[skip ci]') == false
        run: bash script/version.sh
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}

      - name: Publish
        if: contains(github.event.commits[0].message, '[skip ci]') == false
        uses: "lannonbr/vsce-action@75a30e358888a882724b568c7fcc80d7f087906c"
        with:
          args: "publish -p $VSCE_ACCESS_TOKEN"
        env:
          VSCE_ACCESS_TOKEN: ${{ secrets.VSCE_ACCESS_TOKEN }}
